version: 0.2

env:
  runtime-versions:
    nodejs: 18

phases:
  install:
    commands:
      - echo Installing dependencies

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - npm run export || true

artifacts:
  base-directory: out
  files:
    - '**/*'
